# Generated by Django 5.1.6 on 2025-03-10 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='payment_status',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='vetavailability',
            name='date',
        ),
        migrations.AddField(
            model_name='vetavailability',
            name='available_days',
            field=models.CharField(blank=True, help_text='Comma-separated days (e.g., Monday, Tuesday)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vetavailability',
            name='end_time',
            field=models.TimeField(help_text='End time of availability (e.g., 04:00 PM)'),
        ),
        migrations.AlterField(
            model_name='vetavailability',
            name='start_time',
            field=models.TimeField(help_text='Start time of availability (e.g., 07:00 AM)'),
        ),
        migrations.AlterField(
            model_name='vetavailability',
            name='veterinarian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.veterinarian'),
        ),
    ]
