# Generated by Django 5.1.6 on 2025-03-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_payment_status_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
